### ISSUE TITLE
where is roucool ?!!!1!

### ISSUE THREAD

**Issue by louisquentinjoucla** [lowlighter/gracidea#23]
hello  @lowlighter ,

**Is your feature request related to a problem ?**
yes, I cannot enjoy my freedom.

**Describe the solution you'd like**
- I want to have roucool because with bulbizzare, dracofeu, tortank and pikachu. It's the only ones I want and know btw
- tell me where it is

**Describe alternatives you've considered**
- Have multiples roucool
- Finish Half Life alyx
- come play vr at my home

**Additional context**
I was just about to give a star and say gr8 proj8ct m8 8/8 but I breathed out and said to my self something is missing. So I opened up my laptop, closed it, opened up my phone, called a friend which know pokemon better than me, said it was not right that roucool was missing. I said "I know dude right ?".

**Pseudo code**
```javascript
if(cell.notSea && cell.isEmpty) {
    const rand = Math.random()
    if(rand > 0.9999999999999)
        spawnRoucool()
}
```

![image](https://user-images.githubusercontent.com/28892335/92315464-40fc1400-efe6-11ea-97ab-9ca382c7ddcc.png)

goodbye

**Comment by AndrewDaGuy** [comment]
0_0
